services:
  - type: web
    name: siadmin
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/siadmin-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: siadmin_app.ntacdttgxheihhmhsxls
      - key: DB_PASSWORD
        sync: false
      - key: SIADMIN_ADMIN_USERNAME
        value: admin
      - key: SIADMIN_ADMIN_PASSWORD
        generateValue: true
